--ORACLE SQL

/* Observações de implmentação + dúvidas

    1) Com relação aos tipos para dados basicos (CEP, NUMERO, TELEFONE, etc), qual seria a quantidade ideal
    de caracteres para cada um? (ex: CEP = 8, NUMERO = 5, TELEFONE = 11) e o seus tipos (VARCHAR, NUMBER)

    2) CHECK em duas tabelas para garantir consistência ou apenas uma? (ocorre no caso Voluntario e Tipo Voluntario)
*/

CREATE TABLE VOLUNTARIO (
    CPF VARCHAR2(11) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    TELEFONE VARCHAR2(11) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,

    PRIMARY KEY (CPF)
    UNIQUE (EMAIL, TELEFONE)
    CONSTRAINT CHECK_VOLUNTARIO CHECK IN ('AMADOR', 'PROFISSIONAL'),
)

CREATE TABLE TIPO_VOLUNTARIO (
    VOLUNTARIO VARCHAR2(11) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    PRIMARY KEY (VOLUNTARIO, TIPO),
    CONSTRAINT CHECK_TIPO_VOLUNTARIO CHECK IN ('AMADOR', 'PROFISSIONAL'), -- Verificar se é necessário
    CONSTRAINT FK_TIPO_VOLUNTARIO FOREIGN KEY (VOLUNTARIO) REFERENCES VOLUNTARIO(CPF)
)

CREATE TABLE VOLUNTARIO_AMADOR (
    VOLUNTARIO VARCHAR2(11) NOT NULL, --seguindo a modelagem, chamamos de voluntário, mas deveriamos seguir a consistencia de nomes?
    CEP VARCHAR2(10) NOT NULL,
    NUMERO VARCHAR2(10) NOT NULL,
    COMPLEMENTO VARCHAR2(50) NOT NULL,
    PRIMARY KEY (CPF)
    CONSTRAINT FK_VOLUNTARIO_AMADOR FOREIGN KEY (CPF) REFERENCES VOLUNTARIO(CPF),
)

CREATE TABLE VOLUNTARIO_PROFISSIONAL (
    VOLUNTARIO VARCHAR2(11) NOT NULL,
    CRM VARCHAR2(10) NOT NULL,
    PRIMARY KEY (VOLUNTARIO)
    UNIQUE (CRM),
    CONSTRAINT FK_VOLUNTARIO_PROFISSIONAL FOREIGN KEY (VOLUNTARIO) REFERENCES VOLUNTARIO(CPF),
    CONSTRAINT CHECK_VOLUNTARIO_PROFISSIONAL CHECK REGEXP_LIKE(CRM, '[0-9]{2,3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}') -- verificar se é desse formato mesmo
)
